# Butterfly 主题配置

# 导航菜单配置
menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  友链: /links/ || fas fa-link
  关于: /about/ || fas fa-heart

# 网站图标和头像
favicon: /img/favicon.svg
avatar:
  img: /img/avatar.svg
  effect: true

# 主页文章节选
index_post_content:
  method: 3
  length: 300
  excerpt_all: true

# 侧边栏设置
aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  card_author:
    enable: true
    description: '欢迎来到我的博客'
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/LiuziqiOvO
  card_announcement:
    enable: true
    content: 欢迎访问本站，这里会分享一些技术文章和生活感悟。
  card_recent_post:
    enable: true
    limit: 5
    sort: date
  card_categories:
    enable: true
    limit: 8
    expand: none
  card_tags:
    enable: true
    limit: 40
    color: false
    orderby: random

# 文章目录设置
toc:
  enable: true
  number: true
  style_simple: false

# 代码块设置
highlight_theme: mac
code_word_wrap: true
highlight_copy: true
highlight_lang: true

# 社交链接
social:
  Github: https://github.com || fab fa-github
  E-Mail: mailto:your-email@example.com || fas fa-envelope

# 页脚设置
footer:
  owner:
    enable: true
    since: 2024
  custom_text: 感谢访问！
  copyright: true

# 文章版权声明
post_copyright:
  enable: true
  decode: false
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# 评论系统
comments:
  use: Waline
  text: true
  count: true
  lazyload: true

# 页面加载动画
preloader: true

# 图片预览
fancybox: true

# 网页特效
butterfly_article_double_row: true
activate_power_mode: false
fireworks:
  enable: false
  zIndex: 9999
  mobile: false

# 页面动画效果
pacman:
  enable: false
canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: true
  mobile: false

# 搜索功能
local_search:
  enable: true
  preload: false
  CDN:

# 右下角按钮
rightside:
  enable: true
  hide_threshold: 500
  show_percent: true
  total_progress: true

# 社交链接
social:
  fab fa-github: https://github.com/LiuziqiOvO || GitHub
  fas fa-envelope: mailto:your-email@example.com || Email

# 页脚配置
footer:
  owner:
    enable: true
    since: 2024
  custom_text: 
  copyright: true

# 阅读模式
readmode: true

# 夜间模式
darkmode:
  enable: true
  button: true
  autoChangeMode: false

# 自定义样式
inject:
  head:
    - <style>
        .link-card { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; margin: 20px 0; }
        .link-item { background: var(--card-bg); border-radius: 12px; padding: 20px; transition: transform 0.3s; }
        .link-item:hover { transform: translateY(-5px); }
        .link-item a { text-decoration: none; color: var(--font-color); display: flex; align-items: center; }
        .link-item img { width: 32px; height: 32px; margin-right: 15px; }
        .link-item span { font-weight: bold; font-size: 16px; }
        .link-item p { margin: 5px 0 0 47px; color: var(--minor); font-size: 14px; }
      </style>
    - <link rel="stylesheet" href="/css/custom.css">