version: "3"

services:
  hexo:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: hexo-blog
    ports:
      - "4000:4000"
    volumes:
      - ./source:/app/source
      - ./themes:/app/themes
      - ./_config.yml:/app/_config.yml
      - ./_config.butterfly.yml:/app/_config.butterfly.yml
    restart: unless-stopped
